### PR TITLE
rename to match executable

### PR DESCRIPTION
**Pull request by bulian-bg**

### CODE REVIEW

**Comment by bulian-bg** [comment]
otherwise the mod doesn't install

**Comment by critto-bg** [comment]
Huh. And what was the difference with the master? Here's how it is right now on my master:

`tweaks on  master 
➜ git branch
* master

tweaks on  master 
➜ ls -l
total 2072
drwxr-xr-x  8 mac  staff      256 Jun 10 22:38 IATweaks
-rwxr-xr-x@ 1 mac  staff  1057792 Jun  9 13:34 SetupIATweaks.exe`

**Comment by bulian-bg** [comment]
The file name has a hyphen it it; the script calls a file without the hyphen.
     On Thursday, June 11, 2020, 02:17:17 AM EDT, critto <notifications@github.com> wrote:  
 
 


Huh. And what was the difference with the master? Here's how it is right now on my master:

`tweaks on  master
➜ git branch
   
   - master

tweaks on  master
➜ ls -l
total 2072
drwxr-xr-x 8 mac staff 256 Jun 10 22:38 IATweaks
-rwxr-xr-x@ 1 mac staff 1057792 Jun 9 13:34 SetupIATweaks.exe`

**Comment by critto-bg** [comment]
But there's no hyphen right now in the master. Or do you mean that there should be a hyphen?

**Comment by critto-bg** [comment]
Merged.

**Pull request closed without merging**
